### ISSUE TITLE
icinga2cmd not found on icingaweb2 machine.

### ISSUE THREAD

**Issue by usmanC9** [patrickpr/trapdirector#1]
In a multinode environment where icinga2 and icingaweb2 are installed on different machines, the actions performed by icinga2cmd command will not work as it is located on icinga2 machine.

Actions should be performed by icinga2 rest api rather than icinga2cmd command so that they can remotely executed.

**Comment by patrickpr** [comment]
I'll add this as an option (use icingacmd or API).
Thanks for the feedback.

**Comment by patrickpr** [comment]
Hi,

Option is now pushed on master, feel free to test it !
