### ISSUE TITLE
Error when attempting to change log settings.

### ISSUE THREAD

**Issue by jeffstrahl** [patrickpr/trapdirector#10]
**Get debug logs**
Trapdirector -> Status&Mibs -> Status : set Log level to ALL
Insert debug logs from syslog or file depending on your log destination

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Your Environment:**
* trapdirector version (in icinga web 2 : System - About): 1.0.1
* Icinga Web 2 version and modules (in icinga web 2 : System - About): 2.7.1
* Icinga 2 version (`icinga2 --version`): r2.10.5-1
* Operating System and version: Centos 7
* Webserver, PHP versions: 7.1.8

**Additional context**
When attempting to change the log settings to "debug" in order to catch more log information, to open another issue, after I hit save, the Icinga Web gui presents an error in the red banner at the bottom of the browser: error[object Object]

This also happens when I try to adjust the database trap retention from 60 days to 30 days.

While it seems like a permissions problem, or something similar, I do not have any visibility into what's causing this issue.

If you'll let me know what I can do to further troubleshoot, I'll provide whatever information I can.

Thanks,
-jeff

**Comment by patrickpr** [comment]
Hi,

It seems there is a error in php code that javascript is unable to display.

Can you track the server response ? 
If you use Firefox :
- Hit F12 key to open dev tools
- Go to "network" on the dev tools windows : you maybe need to activate network 
- reproduce the problem on main firefox window
- On dev window, locate "logdestination" or "dbmaintenance" (depending on what you are testing) request, and click on it
- Send me the the content of "response" tab

Patrick

**Comment by jeffstrahl** [comment]
Hey Patrick,
Here's the output from firefox, when trying to change the log destination:

Request URL:https://ic2web1.gvec.org/icingaweb2/trapdirector/helper/logdestination
Request method:POST
Remote address:192.168.118.111:443
Status code:
404
Version:HTTP/1.1
Referrer Policy:no-referrer-when-downgrade

Here's the output from performing the DB maintenance:

Request URL:https://ic2web1.gvec.org/icingaweb2/trapdirector/helper/logdestination
Request method:POST
Remote address:192.168.118.111:443
Status code:
404
Version:HTTP/1.1
Referrer Policy:no-referrer-when-downgrade

Thanks,
-jeff

**Comment by patrickpr** [comment]
Hi,

So you have a 404 (not found) error when javascript is saving the information : 
1)  Is your url path for trapddirector correct ? When you are on status page, the url is : 
https://ic2web1.gvec.org/icingaweb2/trapdirector/status/  
?

2) If you enter this URL : https://ic2web1.gvec.org/icingaweb2/trapdirector/helper/logdestination, you should see json reply with somthing like : "status  : "No destination". 
Is it the case ?

/Patrick

**Comment by jeffstrahl** [comment]
I get "page not found" for both of those urls.

I don't think I missed any of the installation steps, but that's always a possibility. I basically cloned the repo down to my server, moved into /usr/share/icingaweb2/modules/trapdirector and followed the install guide. 

So, did I do something incorrectly or is something otherwise missing?

Thanks Patrick,
-jeff

**Comment by patrickpr** [comment]
Hi,
You must have a specific URL for icingaweb2 : can you send me the url when you are on "status & mibs" page ?

**Comment by jeffstrahl** [comment]
https://ic2web1.gvec.org/trapdirector/status/

I see the problem. It's missing the "icingaweb2" piece. If I remove "icingaweb2" from both urls from above, they both work properly.

Is there a setting within the module that I can change to reflect that? I don't see that as an option.

Thanks

**Comment by patrickpr** [comment]
The problem comes from the javascript which doesn't get the correct path.
I'll make a quick patch this evening (it was in my todo list anyway).

**Comment by patrickpr** [comment]
I changed the URL in javascript for some pages and commited to master : refresh your installation with latest "master" branch and it should be OK.
Changes are all in the library/views/scripts directory.

**Comment by jeffstrahl** [comment]
Thanks!
This fixed the problem. I will go ahead and close this issue now. And now, on to issue #11 

Thanks 👍
