### ISSUE TITLE
Database query problem when updating MIBs

### ISSUE THREAD

**Issue by jeffstrahl** [patrickpr/trapdirector#11]
**Get debug logs**
Trapdirector -> Status&Mibs -> Status : set Log level to ALL
Insert debug logs from syslog or file depending on your log destination

**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior: When attempting to import more MIBs, I receive the following error (on CLI): Error in updating : PDO::query(): MySQL server has gone away

The MySQL server & database are still reachable, so it seems like there is a conflict somewhere. If I drop the database, re-add it, and then scan all of the same MIB files in, it works perfectly, I am just unable to add any more MIB files. So, I haven't attempted to build any rules or the such until this piece is figured out, for I don't want to cause a bunch of rework. I would provide log files and more information, but if you'll note BUG #10, I am unable to change the log settings via the web interface.

**Expected behavior**

**Your Environment:**
* trapdirector version (in icinga web 2 : System - About): 1.0.1
* Icinga Web 2 version and modules (in icinga web 2 : System - About): 2.7.1
* Icinga 2 version (`icinga2 --version`): r2.10.5-1
* Operating System and version: Centos 7
* Webserver, PHP versions: 7.1.8

**Additional context**
This is the same database server that icingaweb2 uses, so if there were a problem with the database server, I would suspect that I would see errors there as well, but I do not, so this seems to be exclusive to the trapdirector application.

Please let me know how I may assist with the troubleshooting process.

Thanks

**Comment by patrickpr** [comment]
Thanks for the report, I'll take a look at this shortly.

**Comment by jeffstrahl** [comment]
Hey Patrick,
For this one, I have tried to turn on file logging, but that doesn't appear to be working properly (nothing happens). The web interface saves it now, as it should, but nothing gets logged to /tmp/trapdirector.log. I tried touching the file first, but nothing changes. Then, when I set it to syslog, I don't see anything in there related to trapdirector. So, if you can advise me on how to get you more information, I am more than willing to do what I can.

Thanks,
-jeff

**Comment by patrickpr** [comment]
When updating MIBs on cli, logging is forced to 'display' and level to 'warning' so user can have output.
I'll make a verbose option to display all logs.

**Comment by patrickpr** [comment]
Don't have much time these days : could you change line 57 of file trapdirector/application/clicommands/MibCommand.php

From :  $trap->setLogging(2,'display');
To :      $trap->setLogging(4,'display');

This will force debug output (level 4) on display for the cli update command.

Then, send me the output.

Patrick.

**Comment by jeffstrahl** [comment]
Hey Patrick,
I made the change to the file, ran the command, and here is the output:

[root@ic2web1 clicommands]# icingacli trapdirector mib update
Update main mib database :
[2019/09/25 14:17:37] [trap_class.php] : SQL query : SELECT * from traps_mib_cache;
...#..............................#......##Error in updating : PDO::query(): MySQL server has gone away
[root@ic2web1 clicommands]#

So, not too much more information there, but maybe you'll see something that is incorrect.

Thanks,
-jeff

**Comment by patrickpr** [comment]
Hi,
I need to change the mib update function to get more logs.
Can you check : 
- If Mysql is generating error logs
- The ' wait_timeout" value of mysql using 'mysqladmin variables'

Patrick

**Comment by jeffstrahl** [comment]
Hey Patrick,
Logging is disabled, and here is the 'wait_timeout' value:

MariaDB [mysql]> show variables like 'wait_timeout';
+---------------+-------+
| Variable_name | Value |
+---------------+-------+
| wait_timeout  | 28800 |
+---------------+-------+
1 row in set (0.001 sec)

Thanks

**Comment by patrickpr** [comment]
Hi,
Ok, so timeout is really big : I managed to reproduce the issue with a short timeout.

Anyway, I just added a lot of debug along with a database automatic reconnect : 
- Update your installation with latest master branch
- Run : icingacli trapdirector mib update --verb
(Note : --verb option puts log level to debug).

Thanks for testing.

Patrick

**Comment by jeffstrahl** [comment]
Hey Patrick,
I started the debug this morning, and it finally finished after lunch. The weird thing is that it looks like it finished. There's a "Done : " at the end. I don't remember what a successful import looks like, but I don't see any of the mysql error from before.

Here is the debug (hopefully it attaches as it should).

[trapdirector-debug.txt](https://github.com/patrickpr/trapdirector/files/3664108/trapdirector-debug.txt)

One question that this brings to mind is after a successful import, should I delete the MIB files from the directories, to prevent them from having to be scanned every time? Or does the application delete them from the database if they are not found in the directories? It just seems like it would be more efficient if they only had to be scanned initially, rather than every time we need to introduce another vendor or more MIB files. But, I guess the next challenge would be how to remove legacy MIB files or vendors that are removed from the network. I don't know that I have an answer to that one; more just typing out loud.

Thanks,
-jeff

**Comment by jeffstrahl** [comment]
Just following up on this, I have attached a run without the "--verb" option. It worked successfully, but I did notice a number of "[trap_class.php] : Databse connection lost, reconnecting' which is new.

[trapdirector-works.txt](https://github.com/patrickpr/trapdirector/files/3664499/trapdirector-works.txt)

I'm just trying to provide any feedback that might be useful.

Thanks,
-jeff

**Comment by patrickpr** [comment]
Hi,
I noticed too the 'reconnecting' which is weird considering the wait_time (28800 = 8 hours) and the time for traps part (< 2H) : there must be some other timeout somewhere.

Yes, the system rebuilds part (not all) of the database because MIBs can change with software 
versions.... So you need to have all of them.

As you have about 1690 traps and 7222 objects it currently takes time to process, but notice the TODO in the mib update function : ' this stuff needs some optimization ' :)

/Patrick

**Comment by jeffstrahl** [comment]
Then on Monday, I’ll have one of my system administrators take a look at the process flow to see if we can figure out where the timeout might be.

I’ll keep you posted on our findings.

Thanks

________________________________

**Comment by jeffstrahl** [comment]
Hey Patrick,
One of my system administrators is still looking into this and working on the systems. Once they get the environment more optimized, I'll update you on our findings.

Thanks

**Comment by jeffstrahl** [comment]
Hey Patrick,
I believe we got this working now. There were some session limits on the database server, and we did some more things to further optimize the database. I think we're good now.

I'll go ahead and close this issue.

Thanks for your help,
-jeff
