### ISSUE TITLE
Path name correction

### ISSUE THREAD

**Issue by jeffstrahl** [patrickpr/trapdirector#14]
Hey Patrick,
I didn't know how else to categorize this, but in your Install guide, under "Set up mibs", you are missing an 's' in your path statements.

You have: /usr/share/icingaweb2/module/trapdirector
It should be: /usr/share/icingaweb2/modules/trapdirector

This is in all occurrences of the path in this section.

Just letting you know,
-jeff

**Comment by jeffstrahl** [comment]
Also, I don't know if you're aware or not, but it appears that your links between the docs are broken. I see the broken link symbols throughout.

**Comment by patrickpr** [comment]
Hi,
Thanks for the feedback : I changed the /module typo.
For the links, it actually works for me.
When I try with another browser, I get weird image before the links, but when I click on it, it works : is it the same for you ?
I will investigate on the weird picture before the link.

/patrick

**Comment by patrickpr** [comment]
I figured it out : all my links where using the "image" links ( `![text](link)` ) but i must use "normal" links for text links (without "!").
It wasn't showing this icon on firefox....

Thanks to you for noting this  !

/Patrick
