### ISSUE TITLE
Trap Handler Question

### ISSUE THREAD

**Issue by jeffstrahl** [patrickpr/trapdirector#15]
Hello Patrick,
Now that I think I've got the kinks worked out, I have a question about this before I start configuring rules and the such. How do I create trap handlers for a number of like devices? In other words, we have a number of access platforms, made by the same vendor, using the same MIBs. Is that where I create the trap rules against the Host Group? Will the source name of the alarming device still come through, or will it be the IP?

I would like to create the rules based on the type of device, rather than every single instance of that device.

Thanks in advance,
-jeff

**Comment by patrickpr** [comment]
Hi,

Yes, this is what hostgroup selection in handlers are for.
You must a have in Icinga at least one service which is assigned to all of the hosts in the hostgroup.
 
Then, on a new handler :  
- You select the hostgroup
- The system will display in services dropdown all services that are common to hostgroup hosts : select the one you want to receive passive checks from trapdirector.
- Trap selection and rule is the same as for a single host.

When a trap is received and oid matches the handler you just created : 

- It will get all IP address of all hosts in hostgroup and check if the source IP is one of them
- If it is the case, it will evaluate the rule and depending on rule eval, will make an action
The action (ok/warn/crit) is then sent to Icinga concerning the host that matches the source IP, for the service defined in the handler.
And yes, the name of the host will be shown, not the hostgroup name (the information of the hostgroup is not kept).

/Patrick

**Comment by jeffstrahl** [comment]
Ok thanks. I'll configure it accordingly and we'll see how it works. 

Thanks!
