### ISSUE TITLE
Host/Hostgroup losing the service

### ISSUE THREAD

**Issue by jeffstrahl** [patrickpr/trapdirector#17]
Hey Patrick,
First of all, I didn't open this as a Bug, for it may be me not fully understanding everything completely, but it appears to be a bug. I'll let you decide.

**Configuration:**
I have a NetBotz temperature sensor that I am using to test with, for it gives me the ability to send test traps from it. So, I have the NetBotz configured in Icinga as a host, but also a member of a hostgroup "Sensors". I have the SNMP trap collection template applied to the hostgroup via a service-apply template.

**What I'm seeing:**
When I send a test trap, it comes in properly. When I attempt to build a trap handler against the host name, everything works, however, when I go down to change the action if the rule matches, the interface changes the Service back to "Ping". So, the workaround there is to configure everything, and then set the Service to "NetBotz SNMP Traps". Once I do that and fire off a test trap, the trap is processed correctly.

So, then I want to test sending to a hostgroup. So, I delete the previous host trap handler and build the exact same handler against the hostgroup. When I fire off a test trap against this handler, nothing happens in Icinga. The trap does not show up. I know the trap is reaching the box, for it's showing up in tcpdump, as before. When I click on the trap handler to verify everything, I get an error at the bottom of the Icinga window: "Service NetBotz doesn't exists anymore". But when I click the Service dropdown, "NetBotz SNMP Traps" service is able to be selected. So, I click update, but when I go back into the trap handler, I receive the same error as before and no traps are collected or processed for anything defined in this handler. I also do not get any notification that the trap was received. It just seems to go into a blackhole at that point.

So, like I said, I may be either doing something incorrectly or missing something. That's the part that I don't know.

I appreciate your help with all of this.

/jeff

**Comment by patrickpr** [comment]
Hi,

Looks like a bug : what is the versino you are using ?

**Comment by jeffstrahl** [comment]
Here are the versions of everything:

icinga2: r2.10.5-1
icingaweb2: 2.7.1
trapdirector: 1.0.1
OS: CentOS Linux release 7.6.1810
Web Server: Apache/2.4.6 (CentOS)
PHP version: 7.1.8

Let me know if I can provide any other information.

Thanks,
-jeff

**Comment by patrickpr** [comment]
I'll take a look this week, I now have all info.
I'm currently working on MIB updates optimization (for now time/2 on full scan and time/20 on single file update ! ) but I'll take a look after.

/Patrick

**Comment by patrickpr** [comment]
Bug no1 : service updates when changing actions is corrected in master.

**Comment by patrickpr** [comment]
Bug no2 : if the service in hostgroup has spaces in it's name, it wasn't saved correctly.

**Comment by patrickpr** [comment]
Just to check : with the bug, did you see the trap in "received" tab ? It should be the case and the status detail should say "Error sending status : check cmd/API".

**Comment by jeffstrahl** [comment]
I'll update my local version next week. It's been a crazy day.

In response to your last question, the trap would not show up in the received tab, but it would show up in tcpdump. Once I deleted the handler, it would show up in received.

**Comment by patrickpr** [comment]
Hi,
Did you have time to check the update ?

**Comment by jeffstrahl** [comment]
I had a chance to check the importing of MIBs, and that part is much faster now. Well done. I haven’t had a chance to check the trap configuration piece, for I have been traveling for work. I will work on that early next week.

Thanks
-jeff

________________________________

**Comment by patrickpr** [comment]
Closing case. Feel free to reopen it on related issues.
