### ISSUE TITLE
unable to add hosts

### ISSUE THREAD

**Issue by Pio84** [patrickpr/trapdirector#2]
I have installed it on Ubuntu 18.04 and for some reasons iam unable to add hosts.
I receive traps and snmptranslate works also fine but i cant add an handler without an host.

**Comment by patrickpr** [comment]
Hi,

What exactly isn't working, and how are you doing it : 
- Are you trying to add a trap handler  ? From scratch or from an existing trap ?
- Is there problems with the "Host name" input in this form ? 
- Is there an error displayed when you click "create" ?

Regards,
Patrick

**Comment by patrickpr** [comment]
Closing issue, feel free to reopen or submit a new one when you have the informations I asked for.
