### ISSUE TITLE
Option to run API call instead of passive check.

### ISSUE THREAD

**Issue by SgtSiff** [patrickpr/trapdirector#20]
I'm not sure if this is possible, but instead of submitting a passive check to a service, it would be good if instead, an API call could be made.

For example in my situation where I am monitoring UPS input voltage, instead of receiving a trap, and submitted a passive check result to the service, the following would happen:

Trap is received -> Trap handler sees the trap -> Run API call rule.

So when a trap is received saying that there is a new alarm entry added (mains fail), it would run the following API call:

`curl -k -s -u username:password -H 'Accept: application/json' \
 -X POST 'https://localhost:5665/v1/actions/reschedule-check' \
 -d '{ "type": "Service", "filter": "service.name==\"UPS Input Voltage L1\"", "force": true, "pretty": true }'`

This  allows the critical/warning etc to be determined by thresholds in the commands you have set up. Also, if using Grafana or similar, it should update the graph with appropriate data. Currently, I experience the following:

https://imgur.com/a/gpD7JTC

So instead of a value (e.g. 230) the plugin output it whatever I choose in the trap director. Grafana is unable to display this and despite seeing numerous critical warnings in the history for the service, as far as it is concerned, it has always been 236V or similar.

Thank you

**Comment by patrickpr** [comment]
Hi,

Triggering an action on trap received can be done with event handlers : 
- Create a specific service for the trap on the host.
- Attach an event handler which in your case will trigger a service check.

So when a trap triggers the rule, the trap service will go on warning/critical state and trigger the event handler.
[Icinga doc on event handlers](https://icinga.com/docs/icinga2/latest/doc/03-monitoring-basics/#event-commands)

**Or**

You can also send performance data with the trap display : 

If the trap also sends information about voltage in a specific OID (I will call it $1$), set the display to : 

"Voltage trap received | voltageL1=$1$"

Note : you must have the same name ("voltageL1") than the one output  by your active check.

**Then** 

Tell me what's working best, document it & make a pulll request for others to reproduce :-) 

I'm also working on "hooks" for trap processing but this will take some time and the two solutions above seems better for this case.


/Patrick

**Comment by SgtSiff** [comment]
Once again, you the man Patrick,

Thank you, I will give this a go and report back.

Regards

Joe

**Comment by p4k8** [comment]
Sending perfdata in a display field in format of
`Voltage trap | trapres=$1$`
Where $1$ equals 220
Results in check output display
`Voltage trap | trapres=220`
Without setting performance data
Version 1.0.2

**Comment by patrickpr** [comment]
@p4k8 : transfered to issue #22

**Comment by patrickpr** [comment]
Closing case. Feel free to reopen it on related issues.
