### ISSUE TITLE
MIB Upload fails

### ISSUE THREAD

**Issue by bitboy85** [patrickpr/trapdirector#21]
Hi,
I'm running the recent version of raspbian, icinga2 and trap director.

I've set up the folder permissions for  /usr/share/icingaweb2/modules/trapdirector/mibs/ as documented. Just used www-data instead of apache.
The command  sudo -u www-data touch  /usr/share/icingaweb2/modules/trapdirector/mibs/abc.mib works but uploading through Webgui fails.
I've even tried sudo chmod -R 777 /usr/share/icingaweb2/modules/trapdirector/mibs with no luck.

**Comment by patrickpr** [comment]
Hi,

Is there an error message in the GUI / web server logs / icingaweb logs ?

Patrick

**Comment by bitboy85** [comment]
Hi,

The Webgui only says i should check file permission.

In apache i found this, but the issue is not logged while uploading but when starting apache

> [Thu Dec 19 10:12:04.151521 2019] [core:notice] [pid 785] AH00094: Command line: '/usr/sbin/apache2'
sh: 1: net-snmp-config: not found
cat: '/usr/share/icingaweb2/modules/trapdirector/mibs/*': Datei oder Verzeichnis nicht gefunden
cat: '/.snmp/mibs/*': Datei oder Verzeichnis nicht gefunden
cat: /usr/share/snmp/mibs/iana: Ist ein Verzeichnis
cat: /usr/share/snmp/mibs/ietf: Ist ein Verzeichnis
cat: '/usr/share/mibs/site/*': Datei oder Verzeichnis nicht gefunden
cat: /usr/share/snmp/mibs/iana: Ist ein Verzeichnis
cat: /usr/share/snmp/mibs/ietf: Ist ein Verzeichnis
cat: '/usr/share/mibs/iana/*': Datei oder Verzeichnis nicht gefunden
cat: '/usr/share/mibs/ietf/*': Datei oder Verzeichnis nicht gefunden
cat: '/usr/share/mibs/netsnmp/*': Datei oder Verzeichnis nicht gefunden

**Comment by patrickpr** [comment]
I added some tests and information output in the upload process : please update trapdirector with latest master release and try again.
I suspect your configuration of mib path might not be correct. The patch will tell you exactly what it is.

**Comment by bitboy85** [comment]
Hi i installed the update and it is working now.
I'm sure i changed the permission of that folder but as i checked today it was root:root again.
Maybe something went wrong at this part as i tried it the first time.

**Comment by patrickpr** [comment]
Nicce it's working, I'll close the case.
