### ISSUE TITLE
Perfdata in a display field does not fill perfdata

### ISSUE THREAD

**Issue by patrickpr** [patrickpr/trapdirector#22]
Sending perfdata in a display field in format of
`Voltage trap | trapres=$1$`
Where $1$ equals 220
Results in check output display
`Voltage trap | trapres=220`
Without setting performance data
Version 1.0.2

_Originally posted by @p4k8 in https://github.com/patrickpr/trapdirector/issues/20#issuecomment-574604195_

**Comment by patrickpr** [comment]
Hi,
Could you put the log level of module in debug and send me the logs ?
I haven't tested this for some time, maybe it's broken due to caracter escaping.

Patrick

**Comment by p4k8** [comment]
How do I turn on debug mode btw?

Could it be related to the fact that API requires has dedicated `performance_data` field separate from `plugin_output`?

**Comment by patrickpr** [comment]
# To set debug logs
Trapdirector -> Status&Mibs -> Status : set Log level to ALL
Insert debug logs from syslog or file depending on your log destination

# Concerning the problem
Yes, the separated perfdata field can be the problem. I'll take a look.

**Comment by patrickpr** [comment]
Give latest commit on master branch a try : it should solve the problem.
It was indeed the API POST that wasn't send correctly.

**Comment by p4k8** [comment]
After applying fix perfdata is transmitted properly.
Thank you.
