### ISSUE TITLE
variable error on trap_in.php

### ISSUE THREAD

**Issue by fromanm1** [patrickpr/trapdirector#24]
# Describe the bug
it's a simple error on a variable name

# To Reproduce
just install trapdirector

# Expected behavior
A error on the trapdirector's module windows on icingaweb

# Your Environment:
*  trapdirector 1.0.2 (in icinga web 2 : System - About):
*  Operating System and version: centos 7 
*  Webserver, PHP versions: apache 2.4, php 7.3

Fix:
replace icingaweb2Etc by icingaweb2_etc 
Ps: I spotted same problem on several files: expr_test.php, db_test.php, HelperController.php by example.

greetings.

**Comment by patrickpr** [comment]
Hi,
Thanks for the bug report.
I actually changed the variables names, but they should be changed everywhere and not raise an error.
What is exactly the error message : variable not found ?

**Comment by fromanm1** [comment]
This is the error.

Undefined offset: 0

#0 /usr/share/icingaweb2/modules/trapdirector/application/controllers/SettingsController.php(157): Icinga\Application\ApplicationBootstrap->Icinga\Application\{closure}(Integer, String, String, Integer, Array)
#1 /usr/share/icingaweb2/modules/trapdirector/application/controllers/SettingsController.php(226): Icinga\Module\Trapdirector\Controllers\SettingsController->check_icingaweb_path()
#2 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action.php(507): Icinga\Module\Trapdirector\Controllers\SettingsController->indexAction()
#3 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch(String)
#4 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#5 /usr/share/php/Icinga/Application/Web.php(300): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#6 /usr/share/php/Icinga/Application/webrouter.php(99): Icinga\Application\Web->dispatch()
#7 /usr/share/icingaweb2/public/index.php(4): require_once(String)
#8 {main}

**Comment by patrickpr** [comment]
The problem was in path detection in the module settings. 
Please update with last master branch and check.

**Comment by fromanm1** [comment]
tested, it's working fine!
