### ISSUE TITLE
check snmptrapd configuration (code 3/OID)

### ISSUE THREAD

**Issue by cristobal85** [patrickpr/trapdirector#26]
I recieve traps, but all of them have the same status and status detail. Status is **error** and status detail is **No trap oid found : check snmptrapd configuration (code 3/OID)**. In my configuration, I see only one warning message **snmptrapd has no -n option : -Lsd -f -p /run/snmptrapd.pid**.

# My Environment
If related to the question in any way : 
*  trapdirector version (in icinga web 2 : System - About): 1.0.2
*  Icinga Web 2 version and modules (in icinga web 2 : System - About): 
  incubator | 0.5.0
  ipl | v0.4.0
  monitoring | 2.7.3
  reactbundle | 0.7.0
  translation | 2.7.3
  trapdirector | 1.0.2
*  Icinga 2 version (`icinga2 --version`): r2.11.2-1
*  Operating System and version:
  Platform: Debian GNU/Linux
  Platform version: 10 (buster)
  Kernel: Linux
  Kernel version: 4.19.0-6-amd64
  Architecture: x86_64
*  Webserver, PHP versions:
  Apache2.4 / PHP7.3

**Comment by patrickpr** [comment]
Hi,

The message means snmptrap daemon doesn't have the correct startup options (see [installation doc](https://github.com/patrickpr/trapdirector/blob/master/docs/01-install.md#edit-the-launch-options-of-snmptrapd) ).

You must add "'-n" to your startup options (along with "-Lsd -f -p /run/snmptrapd.pid') so trapdirector can read traps correctly.

**Comment by cristobal85** [comment]
Hi,
I read the documentation but in Debian 10 is different. You must to change the file `/lib/systemd/system/snmptrapd.service` and add options `-n -t -Oen` between `-Lsd` and `-f -p`.
