### ISSUE TITLE
Multiple Regexp oid objects gives same shortcut

### ISSUE THREAD

**Issue by NeverUsedID** [patrickpr/trapdirector#29]
# Describe the bug

A Picture says more then 100 words :) 
![image](https://user-images.githubusercontent.com/7545210/76621375-8526c400-652f-11ea-99c7-4576f68ab853.png)

# To Reproduce
Add 2 rexep oids in a existing  trap handler with no non regexp oid between.

# Expected behavior
Numbers are counting up

# Your Environment:
*  trapdirector version (in icinga web 2 : System - About): 1.0.3
*  Icinga Web 2 version and modules (in icinga web 2 : System - About):
*  Icinga 2 version (`icinga2 --version`): 2.11.3
*  Operating System and version: Ubuntu
*  Webserver, PHP versions:

# Additional context

**Comment by patrickpr** [comment]
Thanks for the bug report, changes has been made in master branch to correct this : update with latest master branch and close this if all is OK.

**Comment by NeverUsedID** [comment]
Now it works with $1$ - $2$.

Thanks a lot. Great solution for Traps!

![image](https://user-images.githubusercontent.com/7545210/76762224-26f91b80-6791-11ea-8efc-c36aa625045a.png)
