### ISSUE TITLE
trap handler fails for hostgroup

### ISSUE THREAD

**Issue by lazyfrosch** [patrickpr/trapdirector#40]
## Get debug logs

```
[2020/07/06 10:12:52] [TrapDirector] [Error]: Connection failed to IDO : invalid data source name
[2020/07/06 10:12:52] [TrapDirector] [Warning]: Exception : [TrapDirector] [Error]: Connection failed to IDO : invalid data source name
```

## Describe the bug

`setupIDO` seems to be executed to be used by hostgroups, should only happen when an Icinga 2 API connection is configured.

The culprit should be:

https://github.com/patrickpr/trapdirector/blob/ba4b05e5c09eadfd21ac319a3f989747b42a125e/library/Trapdirector/TrapsProcess/TrapConfig.php#L176

We should setup the IDO data regardless of if the API is configured here.

## Your Environment:
*  trapdirector version (in icinga web 2 : System - About): 1.0.4-3-gba4b05e
*  Icinga Web 2 version and modules (in icinga web 2 : System - About): 2.7.3
*  Icinga 2 version (`icinga2 --version`): 2.11.4
*  Operating System and version: Debian/Alpine in Docker

**Comment by patrickpr** [comment]
Hi,

Thanks for pointing this, seems this is why hostgroup wasn't working.

I'll update master ASAP and make a new release.

Patrick

**Comment by patrickpr** [comment]
Released 1.0.4b version correcting this.
For your information, I am going to get rid of direct IDO queries and only use Icinga API in next versions. (related to issue #39 )

Keeping this open as I need to add hostgroups rules check in travis-ci to be sure it won't happen again.

Patrick

**Comment by patrickpr** [comment]
Version 1.0.4c should correct this : please tell me if all is ok now.

**Comment by patrickpr** [comment]
Closing issue.
Reopen in case of related problems.
