### ISSUE TITLE
Handling of forwarded traps

### ISSUE THREAD

**Issue by manfredw** [patrickpr/trapdirector#41]
# Main question
TrapDirector shows IP address of sending host as trap source, but traps are forwarded by a central trap receiver to Trap Director.
In this case all traps seem to come from the forwarder.
Is there already a feature to use the trap variable snmpTrapAddress (OID .1.3.6.1.6.3.18.1.3) instead of the forwarder IP?

# Purpose
Without this feature it is not possible to map the trap to the originating device within icinga2 when there are forwarders on the way. TrapDirector should be able to use the snmpTrapAddress field.

# Your Environment
If related to the question in any way : 
*  trapdirector version (in icinga web 2 : System - About): 1.04c
*  Icinga Web 2 version and modules (in icinga web 2 : System - About): 2.7
*  Icinga 2 version (`icinga2 --version`): 2.11
*  Operating System and version: Linux, net-snmp as forwarder and receiver/traphandler
*  Webserver, PHP versions: apache, php7

**Comment by patrickpr** [comment]
No feature for this, but simple to implement.
i'm on holydays for two weeks starting tomorow, so I will take a closer look when I return.

**Comment by patrickpr** [comment]
Feature is implemented in latest master version : can you test it ?

For the snmptrapd forwarding, do you use the following configuration  ?
`forward default <IP>`

**Comment by manfredw** [comment]
Yes, `forward default <IP>` in my forwarder's snmptrapd.conf.

Thx for implementation, I will test during the next days.

**Comment by manfredw** [comment]
Great! New code works as expected.

Will it make sense to store the forwarders address?

PS: is it possible that the logging feature is broken? Logfile stays empty...

**Comment by patrickpr** [comment]
I'm not sure if forwarders address is useful, and it's written in logs on DEBUG logging mode if you need to ... debug.
If you have a use case tell me about it.

Log issue will be treated in other issue ( #45 )

**Comment by patrickpr** [comment]
Working -> closing issue
