### ISSUE TITLE
Uncaught Error: Class

### ISSUE THREAD

**Issue by Pio84** [patrickpr/trapdirector#42]
Hi patrickpr,

i try to install trapdirector-1.0.4c on my environment. But get this Error...

`Uncaught Error: Class 'Icinga\Module\Trapdirector\TrapsController' not found in /usr/share/icingaweb2/modules/trapdirector-1.0.4c/application/controllers/SettingsController.php:19
Stack trace:
#0 /usr/share/icingaweb2/library/vendor/Zend/Controller/Dispatcher/Standard.php(352): include_once()
#1 /usr/share/icingaweb2/library/vendor/Zend/Controller/Dispatcher/Standard.php(271): Zend_Controller_Dispatcher_Standard->loadClass('SettingsControl...')
#2 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(56): Zend_Controller_Dispatcher_Standard->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#3 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#4 /usr/share/php/Icinga/Application/Web.php(300): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#5 /usr/share/php/Icinga/Application/webrouter.php(99): Icinga\Application\Web->dispatch()
#6 /usr/s`
**********
`#0 [internal function]: Icinga\Application\Web->Icinga\Application\{closure}()
#1 {main}`

Icinga Web 2 Version
2.8.2
PHP-Version
7.3.21-1+ubuntu18.04.1+deb.sury.org+1
Icinga Programmversion | r2.12.0-1

what am I doing wrong?

best regards
Pio84

**Comment by Pio84** [comment]
Ok, i solved it by myself.
The Problem was the foldername in /usr/share/icingaweb2/modules
Before: trapdirector1.0.4c
After: trapdiretor

*facepalm*

**Comment by patrickpr** [comment]
Re - opening as it should issue some kind of warning and not crash.
I also need to update the doc to be more specific about this.
