### ISSUE TITLE
Sort and filter trap handlers

### ISSUE THREAD

**Issue by manfredw** [patrickpr/trapdirector#43]
**Is your feature request related to a problem? Please describe.**
Many different traps and hostgroups...

**Describe the solution you'd like**
Please implement sorting on host/host group, source ip, trap oid and service name.
Also allow to filter on the above fields.

**Comment by patrickpr** [comment]
Related to Rules in project 1.0.X .
There is also two fields in database not used (comment and category) that will help organizing handlers.

**Comment by manfredw** [comment]
Great, comments and categories will also really help, especial when there are several complex handlers for the same trap with different rules.

**Comment by patrickpr** [comment]
Added filtering and paging for rules.
Next : 
- ordering
- Comment & grouping

Have a try and give me feedbacks

**Comment by patrickpr** [comment]
Ordering is done (click on column). I will put fancy icons some day
Comments are available in GUI and displayed when hovering on handler in list.

**Comment by patrickpr** [comment]
Categories for handlers are implemented.
Added UI configuration in 'status & mibs' -> 'UI config' 
All features need extensive testing !

**Comment by patrickpr** [comment]
In release 1.0.6
