### ISSUE TITLE
Clone trap handlers

### ISSUE THREAD

**Issue by manfredw** [patrickpr/trapdirector#44]
**Is your feature request related to a problem? Please describe.**
Reuse already defined (complex) handlers with slightly different settings.

**Describe the solution you'd like**
Please implement a feature to clone/copy an existing trap handler.

**Comment by patrickpr** [comment]
Done (latest master) : 
1) Click on an existing rule as if you where editing it
2) Change values
3) Click on 'Clone' instead of update.

**Comment by patrickpr** [comment]
Working OK ?

**Comment by manfredw** [comment]
Yes, it works :-)

There's just a little flaw...
After a click on update or clone, a yellow popup notification "Saved" appears in the footer area.
In other icingaweb2 modules these messages disappear automatically after some seconds, but this one must be removed by clicking on it. Can you change this behaviour? You should find a code sample i.e. in IcingaDirector.

**Comment by patrickpr** [comment]
Yes, there must be a class or something in css that makes it fade out with a timer, but I wasn't able to find exactly which one.
I had a look in Director but didn't find anything working. I'm plannig to write a fader with timeout some day it will take less time than reverse engineer the Director code.

**Comment by patrickpr** [comment]
FYI : found how fading notification is done by Icinga, will update all pages.
