### ISSUE TITLE
API Master

### ISSUE THREAD

**Issue by manfredw** [patrickpr/trapdirector#45]
# Get debug logs
Log settings seems not to work (syslog or file), but the following messages are found in syslog:
[TrapDirector] [Warning]: No node in config file: /etc/icingaweb2/modules/trapdirector/config.ini
[TrapDirector] [Warning]: Unknown node status  : setting to MASTER

# Describe the bug
Unknown

# To Reproduce
Comes with every new trap.

# Expected behavior
No warning during normal operations.

# Your Environment:
Trapdirector (branch master 2020-08-31) running on:
icinga2 2.11.2-1
icingaweb2 2.7.3
apache 2.4, php7.2.5

**Comment by patrickpr** [comment]
I started to implement the HA feature of trapdirector related to issue #32 . This log will be gone when fully implemented (and correcly configured !).

**Comment by patrickpr** [comment]
About the log settings, it might be related to forced debug. I'll have a look.

**Comment by patrickpr** [comment]
Get latest master version, I changed the log to default (as configured in status & mibs) : tell me if the logs are OK.

**Comment by manfredw** [comment]
Why do you try to implement a HA feature in trapdirector?

Many network devices support only a very low number of trap receivers.
So I decided to use a cluster managed virtual IP on my (central) Icinga2 nodes. This offers not only a single point of contact to icingaweb2, it also solves the problem of receiving snmp traps within a HA cluster. All HA nodes share the same software (net-snmp, webserver with icingaweb2 and trapdirector) and configuration, but only the node with the virtual ip will receive the traps.
This concept will also work with satellite nodes by forwarding the traps to your central cluster from each satellite.

**Comment by patrickpr** [comment]
HA feature is needed to be aligned with HA in Icinga.
The virtual IP for trap receiver is what I was planning (see issue #32 )
Your solution works ( and it's simple as I like them) but I also need to have local trap evaluation in satellites and in case of HA Icinga master, I need the satellites to know where to push results/get configuration.

Opened a topic here to talk about it : https://community.icinga.com/t/trapdirector-ha-feature/5439

Are the logs OK ?

**Comment by patrickpr** [comment]
Open the case again in case of related problem.
