### ISSUE TITLE
Undefined variable: count

### ISSUE THREAD

**Issue by Pio84** [patrickpr/trapdirector#48]
# Main question
Klick on Traps->Status & Mibs -> Plugin management cause the following error.

I found a menu in the docs [https://github.com/patrickpr/trapdirector/blob/master/doc/15-mib.md#ui-configuration](url) named "UI Configuration" that i dont have in my enviroment. Is there any context between the error below and the missing menu? It looks to me as if the file(plugins.phtml) is assembling the layout for the "Plugins Management" page.

# Purpose
setup trapdirector

# Your Environment
If related to the question in any way : 
*  trapdirector version (in icinga web 2 : System - About): 1.0.4c
*  Icinga Web 2 version and modules (in icinga web 2 : System - About): 
    Icinga Web 2 Version: 2.8.2
    monitoring: 2.8.2
*  Icinga 2 version (`icinga2 --version`): r2.12.0-1
*  Operating System and version: 18.04.5 LTS
*  Webserver, PHP versions: Apache/2.4.29 (Ubuntu)

`#0 /usr/share/icingaweb2/modules/trapdirector/application/views/scripts/status/plugins.phtml(26): Icinga\Application\ApplicationBootstrap->Icinga\Application\{closure}(Integer, String, String, Integer, Array)
#1 /usr/share/php/Icinga/Web/View.php(248): include(String)
#2 /usr/share/icingaweb2/library/vendor/Zend/View/Abstract.php(877): Icinga\Web\View->_run(String)
#3 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action/Helper/ViewRenderer.php(904): Zend_View_Abstract->render(NULL)
#4 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action/Helper/ViewRenderer.php(925): Zend_Controller_Action_Helper_ViewRenderer->renderScript(String, NULL)
#5 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action/Helper/ViewRenderer.php(964): Zend_Controller_Action_Helper_ViewRenderer->render()
#6 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action/HelperBroker.php(272): Zend_Controller_Action_Helper_ViewRenderer->postDispatch()
#7 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action.php(518): Zend_Controller_Action_HelperBroker->notifyPostDispatch()
#8 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch(String)
#9 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#10 /usr/share/php/Icinga/Application/Web.php(300): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#11 /usr/share/php/Icinga/Application/webrouter.php(99): Icinga\Application\Web->dispatch()
#12 /usr/share/icingaweb2/public/index.php(4): require_once(String)
#13 {main}`

**Comment by patrickpr** [comment]
Hi,

Actually, both are related because the bug in plugins page is corrected in 1.0.5 and the 'UI Configuration' is also in this next release.

If you want both, you can wait for 1.0.5 to be released (in less than a month) or you can update using latest master (https://github.com/patrickpr/trapdirector/archive/master.zip).

**Comment by Pio84** [comment]
Hmm, ok. Than this has nothing to do with the wrong output in the screenshot below?
![2020-09-10 10_31_29-Window](https://user-images.githubusercontent.com/48513287/92702056-08936780-f351-11ea-9819-d0e732eacb7b.png)

**Comment by patrickpr** [comment]
What is wrong in the output you provided ?

**Comment by Pio84** [comment]
there is no translation, i try to figure out why there are no objects and traps in the mib database.
![2020-09-10 11_21_07-Window](https://user-images.githubusercontent.com/48513287/92710100-c7eb1c80-f357-11ea-8390-c496f52e5fc4.png)

**Comment by patrickpr** [comment]
Ok, so check : 
- You have the Mibs on your system : on cli, do : `snmptranslate .1.3.6.1.6.3.1.1.5.1` , it should answer : `SNMPv2-MIB::coldStart`
- Try updating the mib database : either click "Update mib database" in the GUI or on cli : ` icingacli trapdirector mib update`

**Comment by Pio84** [comment]
i've done this several times, with success...
![2020-09-10 12_14_38-Window](https://user-images.githubusercontent.com/48513287/92716699-747ccc80-f35f-11ea-9828-bb9bc062b9cd.png)

**Comment by Pio84** [comment]
> Ok, so check :

Du you have any idea how to debug this?

**Comment by patrickpr** [comment]
1) the trap database isn't growing : 
send me the result of `icingacli trapdirector mib update --verb` to see why.

2) Even without the trap database, snmptranslate should do the work in the trap table. 
On the GUI, in 'received' (like the screenshot you send me), click on the trap column. It should ioen a new tab with the trap details, please send me this too.

**Comment by Pio84** [comment]
![2020-09-10 13_51_49-Window](https://user-images.githubusercontent.com/48513287/92725896-1a830380-f36d-11ea-8f17-f43aae02011c.png)
![2020-09-10 13_52_41-Window](https://user-images.githubusercontent.com/48513287/92725901-1ce55d80-f36d-11ea-8dcc-fed454c1e342.png)

**Comment by Pio84** [comment]
Maybe its the MIB File that dont work?
[ASTARO-MIB.txt](https://github.com/patrickpr/trapdirector/files/5201534/ASTARO-MIB.txt)

**Comment by patrickpr** [comment]
Ok, so first thing : in 1.0.4, if a trap OID is not translated when received, it won't display as name in the 'received' table. 
(This will change in next version so this is why I didn't understand at first).

There is a problem with snmptranslate (ASTARO mib you sent seems fine I tested it) as it doesn't return any snmp objects : is there any error when running : 
`/usr/bin/snmptranslate -m ALL -M +/usr/share/icingaweb2/modules/trapdirector/mibs -On -Tto`
?

**Comment by Pio84** [comment]
i have the Output of 
`/usr/bin/snmptranslate -m ALL -M +/usr/share/icingaweb2/modules/trapdirector/mibs -On -Tto`
attached as output.
[output.txt](https://github.com/patrickpr/trapdirector/files/5201624/output.txt)
it seems that here is a problem.
txt, its to much to add as message here

**Comment by patrickpr** [comment]
I will add some more test in the GUI. 

BEFORE adding the missing files cans you try : 
`snmptranslate 1.3.6.1.4` 
`snmptranslate 1.3.6.1.2.1` 

And give me the output ?

**Comment by Pio84** [comment]
snmptranslate 1.3.6.1.4
SNMPv2-SMI::private
snmptranslate 1.3.6.1.2.1
SNMPv2-SMI::mib-2

**Comment by patrickpr** [comment]
Ok, thks. I will make some other tests then.

Found the packages you need ?

**Comment by Pio84** [comment]
> Found the packages you need ?

Yes, i think i found a good tutorial.
https://l3net.wordpress.com/2013/05/12/installing-net-snmp-mibs-on-ubuntu-and-debian/

![2020-09-10 15_55_24-Window](https://user-images.githubusercontent.com/48513287/92740572-21fed880-f37e-11ea-91d8-33d4ad0e547a.png)

**Comment by patrickpr** [comment]
Ok, I'll update the doc.
Can you confirm you only needed to do  
```
sudo apt-get install snmp-mibs-downloader
sudo download-mibs
```

?

**Comment by Pio84** [comment]
You have to:
`sudo apt-get install snmp-mibs-downloader`
and edit `/etc/snmp/snmp.conf` like this:

  1 # As the snmp packages come without MIB files due to license reasons, loading
  2 # of MIBs is disabled by default. If you added the MIBs you can reenable
  3 # loading them by commenting out the following line.
  4 mibs +all

to check if it work you can. 
`snmptranslate -Tp`

thank you very much for your support!

Update of MIB databse is running and progress is visible.

**Comment by patrickpr** [comment]
Ok great, I will update the doc.
 
> to check if it work you can.
> `snmptranslate -Tp`
> 

Do you have the result of the command BEFORE it was OK ?

**Comment by Pio84** [comment]
> Do you have the result of the command BEFORE it was OK ?

Hmmm, strange. i have two systems here, Monitoring-test and Monitoring.
On my test System i have no Traps/Objects in the MIB Database. On the live system (on wich i worked today) the MIB database works now fine. I compared the Output from `snmptranslate -Tp` on the two files and its the same.
[MONITORING.txt](https://github.com/patrickpr/trapdirector/files/5202548/MONITORING.txt)
[MONITORING-TEST.txt](https://github.com/patrickpr/trapdirector/files/5202549/MONITORING-TEST.txt)

**Comment by patrickpr** [comment]
Ok, I will just update the doc and maybe check errors returned in snmptranslate on mib update.

I will let the case open until I finished this.
