### ISSUE TITLE
Host selection when adding trap handler not working

### ISSUE THREAD

**Issue by manfredw** [patrickpr/trapdirector#7]
There are no hosts listed/offered when started typing in field Host name, menu Add trap handler.
Tested with Firefox 68 and Chrome 76.

Also getting confused by announced version 1.0, module reports version 0.9.2.
Branch 1.1 shows same behavior.

Best Regards,
Manfred

PS: great work

**Comment by patrickpr** [comment]
Hi,

(Yes, I forgot to update version to 1.0 and 1.1 branch is still empty, I'll take care of this).

Can you check the ido database set in the module configuration is correct ? 
It should be same than the ressource in the file : /etc/icingaweb2/modules/monitoring/backends.ini

Does the system show any errors ? (syslog / web server error logs) ?

**Comment by manfredw** [comment]
Did some research and found out, that IDO DB was set to wrong DB. After correction there was a green IDO Database OK on the config -> there should be a check when IDO DB did not work.

Now I will try to create rules and get traps sent to application. I've to get familiar with the rules syntax, used snmptt before...

**Comment by patrickpr** [comment]
It's nice it's working now.
I suspected something like this, so I wrote a quick check of ido database in the configuration page this evening (version 1.0.1 branch master) and I will have a look why the other pages didn"t generate errors.

If there are parts in the docs you think needs clarifications , please send me feedback.

**Comment by patrickpr** [comment]
Closing this case as it seems working now
