### ISSUE TITLE
Problems with create schema trapdirector

### ISSUE THREAD

**Issue by twiddy02** [patrickpr/trapdirector#72]
when installing the trapdirector under Icingaweb2 I run into an error at 3. create required database schema:

SQLSTATE[42S02]: Base table or view not found: 1146 Table 'trapdirector.traps_db_config' doesn't exist

#0 /usr/share/icingaweb2/modules/trapdirector/library/Trapdirector/TrapsProcess/TrapConfig.php(97): PDO->query()
#1 /usr/share/icingaweb2/modules/trapdirector/library/Trapdirector/TrapsProcess/TrapConfig.php(84): Trapdirector\Trap->getDBConfig()
#2 /usr/share/icingaweb2/modules/trapdirector/library/Trapdirector/TrapsProcess/TrapConfig.php(65): Trapdirector\Trap->getDBConfigIfSet()
#3 /usr/share/icingaweb2/modules/trapdirector/library/Trapdirector/TrapsProcess/Trap.php(129): Trapdirector\Trap->getDatabaseOptions()
#4 /usr/share/icingaweb2/modules/trapdirector/application/controllers/SettingsController.php(369): Trapdirector\Trap->__construct()
#5 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action.php(507): Icinga\Module\Trapdirector\Controllers\SettingsController->createschemaAction()
#6 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch()
#7 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch()
#8 /usr/share/php/Icinga/Application/Web.php(304): Zend_Controller_Front->dispatch()
#9 /usr/share/php/Icinga/Application/webrouter.php(107): Icinga\Application\Web->dispatch()
#10 /usr/share/icingaweb2/public/index.php(4): require_once(String)
#11 {main}

Where is my error (I'm a newbie in Icingsweb2)

# Purpose
What are you trying to achieve

# Your Environment
If related to the question in any way : 
*  trapdirector version (in icinga web 2 : System - About): 1.0.6 
*  Icinga Web 2 version and modules (in icinga web 2 : System - About): 2.9.5
*  Icinga 2 version (`icinga2 --version`): 2.13.2-1
*  Operating System and version: Red Hat Enterprise Linux 8.7
*  Webserver, PHP versions: php 8.0.26

**Comment by Tqnsls** [comment]
So, at which point of the installation and on which URLs do you receive the errors?
What do the tests say at `/icingaweb2/trapdirector/settings`

**Comment by twiddy02** [comment]
Ic receive the error after the automatic installation.  The configuration page under icingaweb2 says, i should create schema for trapdirector under the Link "Configure it here : [/icingaweb2/trapdirector/settings/createschema](http://10.80.30.172/icingaweb2/trapdirector/settings/createschema)". When I click the link, the error appears.
![trapdirector](https://user-images.githubusercontent.com/121957278/210589485-bfed1e9c-2e01-40ab-9e0b-36d07b60ca35.png)
![trapdirector_error](https://user-images.githubusercontent.com/121957278/210589505-c8e55bdf-7fdd-426a-9468-d47d8822f0ec.png)

**Comment by twiddy02** [comment]
![trapdirector_ressource](https://user-images.githubusercontent.com/121957278/210590370-e6e7e45b-d400-4730-856c-41b0f176b3eb.png)

**Comment by Tqnsls** [comment]
I believe you are using a mysql-user with insufficient permissions.
When I go to `/icingaweb2/trapdirector/settings/createschema` it works immediately.

![image](https://user-images.githubusercontent.com/67681686/210787753-a9bbda97-43b0-4b97-bb47-b72df41c2fe1.png)

**Comment by twiddy02** [comment]
theoretically the mysql-user trapdirector has all rights
![trapdirector_permissions](https://user-images.githubusercontent.com/121957278/210791234-a848dd97-a063-432f-ab30-4b4eace9b607.png)

**Comment by twiddy02** [comment]
When I execute the installer.sh in /usr/share/icingaweb2/modules/trapdirector/bin/ ) get the following error: ./installer.sh: Zeile 404: add_schema: Kommando nicht gefunden. 

Is here the problem?

**Comment by Tqnsls** [comment]
In the 1.0.6 the installer.sh calls the function "add_schema (like you noticed) which does not exist. (https://github.com/patrickpr/trapdirector/blob/1.0.6/bin/installer.sh#L404)
I believe it were sufficient to replace the "add_schema"-calls in the script with "add_schema_mysql" / "add_schema_pgsql" or maybe pull the master-release (1.0.7a atm), the script seems fixed. (https://github.com/patrickpr/trapdirector/blob/master/bin/installer.sh#L404)

**Comment by twiddy02** [comment]
unfortunately that didn't work. The error persists

**Comment by twiddy02** [comment]
Can I create the database schema manually? With what commands?

**Comment by Tqnsls** [comment]
> unfortunately that didn't work. The error persists

You did pull 1.0.7a and re-did all required tasks and it still failed? 

> Can I create the database schema manually? With what commands?

 You did find the SQL-scripts in SQL/, didn't you?

**Comment by twiddy02** [comment]
I installed version 1.07a with all required tasks. The error still exists.

I found the SQL commands

**Comment by twiddy02** [comment]
I was able to fix the problem by manually creating the tables in the sql database. Thanks for the help

**Comment by chupztugz000000000** [comment]
@twiddy02  @patrickpr  can you guide me on how to create schema manually? i have errors like this 
![error3](https://github.com/user-attachments/assets/607bdcf6-277c-4301-b99a-b163efef7192)
![error2](https://github.com/user-attachments/assets/96c67c2f-238e-4850-894b-8a4e04902c41)
![error1](https://github.com/user-attachments/assets/5c045cc7-7e79-445e-96b5-76630e9a8662)

**Comment by chupztugz000000000** [comment]
> I was able to fix the problem by manually creating the tables in the sql database. Thanks for the help

hi what are is the script for this?
