### ISSUE TITLE
Problems with php on trapsdirector

### ISSUE THREAD

**Issue by laison007** [patrickpr/trapdirector#77]
Hello.

Hi, I can't find a way for the traps module to recognize the database I have created for the application, I can't create the schema either, I have numerous errors and I am following the steps in your manual, could you help me?

Icinga Web 2 Version | 2.12.1
Icinga Web 2 Version	2.12.1
PHP Version	8.2.7

Loaded Libraries
icinga/icinga-php-library	0.13.1
icinga/icinga-php-thirdparty	0.12.1

Loaded Modules
director		1.11.0	
doc		2.12.1	
icingadb		1.1.1	
incubator		0.20.0	
migrate		2.12.1	
monitoring		2.12.1	
nagvis		1.1.1	
trapdirector		1.0.6

**Comment by laison007** [comment]
Hello again:

Reviewing other issues, I have advanced in the activation of the module, I had to create the database tables manually, because I could not import the schema, it always gave error.

Now I have several errors:

Inside the module, in the "Handlers" section, all these error messages appear:


Call to undefined method IcingaDataDbConnection::getConnection().

#0 /usr/share/icinga-php/vendor/vendor/shardj/zf1-future/library/Zend/Controller/Action.php(516): Icinga "Module"::TrapDirector "HandlerController"::HandlerController->indexAction()
#1 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch().
#2 /usr/share/icinga-php/vendor/vendor/shardj/zf1-future/library/Zend/Controller/Front.php(954): IcingaWebController->dispatcher->dispatch().
#3 /usr/share/php/Icinga/Application/Web.php(294): Zend_Controller_Front->dispatch().
#4 /usr/share/php/Icinga/Application/webrouter.php(105): Icinga/Application->dispatch().
#5 /usr/share/icingaweb2/public/index.php(4): require_once(String)
#6 {main}

In the Status & Mibs section these appear:

Call to undefined method IcingaDataDbConnection::getConnection().

#0 /usr/share/icingaweb2/modules/trapdirector/application/controllers/StatusController.php(24): Icinga/Module/trapdirector/trapsActions/UIDatabase->getDbConn().
#1 /usr/share/icinga-php/vendor/vendor/shardj/zf1-future/library/Zend/Controller/Action.php(516): Icinga/Module/Trapdirector/Controllers/StatusController->indexAction().
#2 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch().
#3 /usr/share/icinga-php/vendor/vendor/shardj/zf1-future/library/Zend/Controller/Front.php(954): IcingaWebController->dispatcher->dispatch().
#4 /usr/share/php/Icinga/Application/Web.php(294): Zend_Controller_Front->dispatch().
#5 /usr/share/php/Icinga/Application/webrouter.php(105): Icinga/Application->dispatch().
#6 /usr/share/icingaweb2/public/index.php(4): require_once(String)
#7 {main}

And in the main section of the Traps module:

Deprecated
: Return type of IcingaModuleTrapDirector::count() should either be compatible with Countable::count(): int, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in
/usr/share/icingaweb2/modules/trapdirector/library/Trapdirector/Tables/TrapTable.php
on line
138

Can someone help me understand all these error messages?
Thank you very much in advance.

**Comment by laison007** [comment]
Hi, researching I managed to solve the first 2 error messages, changing getConnection to getDbAdapter.
Link here:
https://github.com/patrickpr/trapdirector/issues/70 
#70
Thank you very much.

But I still get this message in the main section:

Deprecated
: Return type of IcingaModuleTrapDirector::count() should either be compatible with Countable::count(): int, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in
/usr/share/icingaweb2/modules/trapdirector/library/Trapdirector/Tables/TrapTable.php
on line
138

Does anyone have this problem?, it seems to me that this is a warning
I indicate again my version of PHP, Trapdirector and Icinga.

Icinga Web 2 Version 2.12.1
PHP Version 8.2.7

Loaded Libraries
icinga/icinga-php-library 0.13.1
icinga/icinga-php-thirdparty 0.12.1

trapdirector		1.0.7a	

Best regards

**Comment by laison007** [comment]
Can someone help me?

**Comment by laison007** [comment]
I have finally solved my problems and I am now receiving traps.

**Comment by leifbln** [comment]
@laison007 could you maybe give a hint what you did to solve it? Would be probably helpful for others (like me) who are experiencing similar issues.

Thank you!

**Comment by 6bIBAET** [comment]
> [@laison007](https://github.com/laison007) could you maybe give a hint what you did to solve it? Would be probably helpful for others (like me) who are experiencing similar issues.
> 
> Thank you!

Replace getConnection() with getDbAdapter() in:
/usr/share/icingaweb2/modules/trapdirector/application/clicommands/MibCommand.php		
/usr/share/icingaweb2/modules/trapdirector/application/clicommands/StatusCommand.php		
/usr/share/icingaweb2/modules/trapdirector/application/controllers/HandlerController.php	       
/usr/share/icingaweb2/modules/trapdirector/library/Trapdirector/TrapsActions/UIDatabase.php
